
version: '3'
services:
  #Postrgres Database
  postgres:    
    image: mdillon/postgis:11
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/:delegated 


  backend:
    build: .
    volumes:
       - .:/code
    depends_on:
      - postgres
volumes:
  postgres_data:

  